export const AUTH_CONFIG = {
  COOKIE_ACCESS_TOKEN_NAME: <string>(
    process.env.NEXT_PUBLIC_COOKIE_ACCESS_TOKEN_NAME
  ),
  COOKIE_REFRESH_TOKEN_NAME: <string>(
    process.env.NEXT_PUBLIC_COOKIE_REFRESH_TOKEN_NAME
  ),
};
